version: "3"
services:
  web:
    build: .
    command: uvicorn raspberries.adapters.api:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8008:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

    restart: on-failure

  postgres:
    image: postgres:14.2
    user: postgres
    environment:
      POSTGRES_DB: "raspberries"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "raspberries" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
